
// Generated by Cadence Encounter(R) RTL Compiler RC14.13 - v14.10-s027_1

// Verification Directory fv/top_interface 

module clock_divider(reset, clk, reds_on_flag, need_white2Tminus_flag,
     need_green2yellow_flag, need_red_flag, white2Tminus_flag,
     green2yellow_flag, red_flag);
  input reset, clk, reds_on_flag, need_white2Tminus_flag,
       need_green2yellow_flag, need_red_flag;
  output white2Tminus_flag, green2yellow_flag, red_flag;
  wire reset, clk, reds_on_flag, need_white2Tminus_flag,
       need_green2yellow_flag, need_red_flag;
  wire white2Tminus_flag, green2yellow_flag, red_flag;
  wire [2:0] state;
  wire [3:0] counter1;
  wire [3:0] counter2;
  wire [3:0] counter;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_76, n_77, n_81, n_82, n_84, n_85;
  LHQ_X1 green2yellow_flag_reg(.E (n_76), .D (n_81), .Q
       (green2yellow_flag));
  LHQ_X1 red_flag_reg(.E (n_76), .D (n_85), .Q (red_flag));
  LHQ_X1 white2Tminus_flag_reg(.E (n_76), .D (n_84), .Q
       (white2Tminus_flag));
  NAND2_X1 g721(.A1 (n_2), .A2 (state[2]), .ZN (n_76));
  NOR2_X1 g722(.A1 (n_77), .A2 (n_74), .ZN (n_81));
  AND2_X1 g723(.A1 (n_82), .A2 (state[2]), .Z (n_85));
  NOR2_X1 g724(.A1 (n_77), .A2 (state[0]), .ZN (n_84));
  NAND2_X1 g725(.A1 (n_73), .A2 (state[1]), .ZN (n_77));
  INV_X1 g726(.I (n_82), .ZN (n_2));
  NOR2_X1 g727(.A1 (state[0]), .A2 (state[1]), .ZN (n_82));
  INV_X1 g728(.I (state[0]), .ZN (n_74));
  INV_X1 g729(.I (state[2]), .ZN (n_73));
  SDFFSNQ_X1 \counter1_reg[0] (.SN (1'b1), .CLK (clk), .D (n_29), .SI
       (n_11), .SE (counter1[0]), .Q (counter1[0]));
  DFFSNQ_X1 \counter1_reg[1] (.SN (1'b1), .CLK (clk), .D (n_45), .Q
       (counter1[1]));
  DFFSNQ_X1 \counter1_reg[2] (.SN (1'b1), .CLK (clk), .D (n_62), .Q
       (counter1[2]));
  DFFSNQ_X1 \counter1_reg[3] (.SN (1'b1), .CLK (clk), .D (n_60), .Q
       (counter1[3]));
  SDFFSNQ_X1 \counter2_reg[0] (.SN (1'b1), .CLK (clk), .D (n_38), .SI
       (n_10), .SE (counter2[0]), .Q (counter2[0]));
  DFFSNQ_X1 \counter2_reg[1] (.SN (1'b1), .CLK (clk), .D (n_55), .Q
       (counter2[1]));
  DFFSNQ_X1 \counter2_reg[2] (.SN (1'b1), .CLK (clk), .D (n_69), .Q
       (counter2[2]));
  DFFSNQ_X1 \counter2_reg[3] (.SN (1'b1), .CLK (clk), .D (n_70), .Q
       (counter2[3]));
  SDFFSNQ_X1 \counter_reg[0] (.SN (1'b1), .CLK (clk), .D (n_39), .SI
       (n_8), .SE (counter[0]), .Q (counter[0]));
  DFFSNQ_X1 \counter_reg[1] (.SN (1'b1), .CLK (clk), .D (n_57), .Q
       (counter[1]));
  DFFSNQ_X1 \counter_reg[2] (.SN (1'b1), .CLK (clk), .D (n_67), .Q
       (counter[2]));
  DFFSNQ_X1 \counter_reg[3] (.SN (1'b1), .CLK (clk), .D (n_72), .Q
       (counter[3]));
  DFFSNQ_X1 \state_reg[0] (.SN (1'b1), .CLK (clk), .D (n_58), .Q
       (state[0]));
  DFFSNQ_X1 \state_reg[1] (.SN (1'b1), .CLK (clk), .D (n_64), .Q
       (state[1]));
  DFFSNQ_X1 \state_reg[2] (.SN (1'b1), .CLK (clk), .D (n_50), .Q
       (state[2]));
  INV_X1 g1559(.I (n_71), .ZN (n_72));
  AOI22_X1 g1560(.A1 (n_65), .A2 (n_39), .B1 (counter[3]), .B2 (n_8),
       .ZN (n_71));
  OAI21_X1 g1563(.A1 (n_63), .A2 (n_37), .B (n_20), .ZN (n_70));
  INV_X1 g1567(.I (n_68), .ZN (n_69));
  AOI22_X1 g1568(.A1 (n_43), .A2 (n_38), .B1 (counter2[2]), .B2 (n_10),
       .ZN (n_68));
  INV_X1 g1569(.I (n_66), .ZN (n_67));
  AOI22_X1 g1570(.A1 (n_53), .A2 (n_39), .B1 (counter[2]), .B2 (n_8),
       .ZN (n_66));
  XOR2_X1 g1571(.A1 (n_52), .A2 (counter[3]), .Z (n_65));
  AOI21_X1 g1577(.A1 (n_40), .A2 (n_51), .B (n_7), .ZN (n_64));
  AOI21_X1 g1578(.A1 (n_22), .A2 (counter2[2]), .B (counter2[3]), .ZN
       (n_63));
  INV_X1 g1579(.I (n_61), .ZN (n_62));
  AOI21_X1 g1580(.A1 (counter1[2]), .A2 (n_48), .B (n_49), .ZN (n_61));
  OAI21_X1 g1581(.A1 (n_42), .A2 (n_30), .B (n_59), .ZN (n_60));
  NAND2_X1 g1585(.A1 (counter1[3]), .A2 (n_48), .ZN (n_59));
  NOR2_X1 g1586(.A1 (n_41), .A2 (n_46), .ZN (n_58));
  INV_X1 g1587(.I (n_56), .ZN (n_57));
  AOI22_X1 g1588(.A1 (n_27), .A2 (n_39), .B1 (counter[1]), .B2 (n_8),
       .ZN (n_56));
  INV_X1 g1589(.I (n_54), .ZN (n_55));
  AOI22_X1 g1590(.A1 (n_21), .A2 (n_38), .B1 (counter2[1]), .B2 (n_10),
       .ZN (n_54));
  HA_X1 g1591(.A (counter[2]), .B (n_26), .CO (n_52), .S (n_53));
  NAND2_X1 g1592(.A1 (n_17), .A2 (n_35), .ZN (n_51));
  NAND2_X1 g1593(.A1 (n_36), .A2 (n_37), .ZN (n_50));
  NOR3_X1 g1594(.A1 (n_25), .A2 (counter1[2]), .A3 (n_30), .ZN (n_49));
  INV_X1 g1595(.I (n_47), .ZN (n_48));
  AOI21_X1 g1596(.A1 (n_25), .A2 (n_29), .B (n_11), .ZN (n_47));
  AOI22_X1 g1597(.A1 (n_31), .A2 (n_13), .B1 (n_4), .B2 (n_6), .ZN
       (n_46));
  INV_X1 g1598(.I (n_44), .ZN (n_45));
  AOI22_X1 g1599(.A1 (n_23), .A2 (n_29), .B1 (counter1[1]), .B2 (n_11),
       .ZN (n_44));
  XOR2_X1 g1600(.A1 (n_22), .A2 (counter2[2]), .Z (n_43));
  NAND2_X1 g1601(.A1 (n_24), .A2 (counter1[2]), .ZN (n_42));
  NOR2_X1 g1602(.A1 (n_33), .A2 (n_34), .ZN (n_41));
  NAND3_X1 g1603(.A1 (n_15), .A2 (n_18), .A3 (state[0]), .ZN (n_40));
  NOR3_X1 g1604(.A1 (n_28), .A2 (n_8), .A3 (reset), .ZN (n_39));
  INV_X1 g1605(.I (n_38), .ZN (n_37));
  NOR4_X1 g1606(.A1 (n_31), .A2 (state[0]), .A3 (state[1]), .A4
       (reset), .ZN (n_38));
  NAND4_X1 g1607(.A1 (n_19), .A2 (state[0]), .A3 (need_red_flag), .A4
       (n_6), .ZN (n_36));
  OAI21_X1 g1608(.A1 (n_9), .A2 (state[1]), .B (n_32), .ZN (n_35));
  OAI21_X1 g1609(.A1 (n_12), .A2 (state[1]), .B (n_17), .ZN (n_34));
  NOR2_X1 g1610(.A1 (n_14), .A2 (n_5), .ZN (n_33));
  NAND2_X1 g1611(.A1 (n_14), .A2 (state[1]), .ZN (n_32));
  NAND2_X1 g1612(.A1 (n_16), .A2 (state[2]), .ZN (n_31));
  INV_X1 g1613(.I (n_30), .ZN (n_29));
  NAND3_X1 g1614(.A1 (n_81), .A2 (n_15), .A3 (n_1), .ZN (n_30));
  HA_X1 g1616(.A (counter[1]), .B (counter[0]), .CO (n_26), .S (n_27));
  INV_X1 g1617(.I (n_24), .ZN (n_25));
  HA_X1 g1618(.A (counter1[0]), .B (counter1[1]), .CO (n_24), .S
       (n_23));
  HA_X1 g1619(.A (counter2[1]), .B (counter2[0]), .CO (n_22), .S
       (n_21));
  NAND2_X1 g1620(.A1 (counter2[3]), .A2 (n_10), .ZN (n_20));
  INV_X1 g1621(.I (n_18), .ZN (n_19));
  NAND2_X1 g1622(.A1 (n_9), .A2 (n_5), .ZN (n_18));
  AOI21_X1 g1623(.A1 (state[0]), .A2 (state[1]), .B (n_82), .ZN (n_17));
  OAI21_X1 g1624(.A1 (counter2[2]), .A2 (counter2[1]), .B
       (counter2[3]), .ZN (n_16));
  OAI21_X1 g1625(.A1 (counter1[2]), .A2 (counter1[1]), .B
       (counter1[3]), .ZN (n_15));
  OAI21_X1 g1626(.A1 (counter[2]), .A2 (counter[1]), .B (counter[3]),
       .ZN (n_14));
  AOI21_X1 g1627(.A1 (n_2), .A2 (n_77), .B (reset), .ZN (n_13));
  NOR2_X1 g1628(.A1 (n_3), .A2 (need_green2yellow_flag), .ZN (n_12));
  NOR2_X1 g1629(.A1 (n_81), .A2 (reset), .ZN (n_11));
  NOR2_X1 g1630(.A1 (n_85), .A2 (reset), .ZN (n_10));
  NOR2_X1 g1631(.A1 (need_white2Tminus_flag), .A2
       (need_green2yellow_flag), .ZN (n_9));
  NOR2_X1 g1632(.A1 (n_84), .A2 (reset), .ZN (n_8));
  INV_X1 g1633(.I (n_6), .ZN (n_7));
  NOR2_X1 g1634(.A1 (state[2]), .A2 (reset), .ZN (n_6));
  INV_X1 g1635(.I (state[1]), .ZN (n_5));
  INV_X1 g1636(.I (need_white2Tminus_flag), .ZN (n_4));
  INV_X1 g1637(.I (need_red_flag), .ZN (n_3));
  INV_X1 g1639(.I (reset), .ZN (n_1));
  INV_X1 g1640(.I (n_14), .ZN (n_28));
endmodule

module fsm(clk, reset, start, pass_key, mess_traffic_flag,
     daytime_flag, white2Tminus_flag, green2yellow_flag, red_flag,
     need_white2Tminus_flag, need_green2yellow_flag, need_red_flag,
     reds_on_flag, EW_straight_lights_flag, SN_straight_lights_flag,
     ES_turning_lights_flag, WN_turning_lights_flag,
     SW_turning_lights_flag, NE_turning_lights_flag,
     EWS_passenger_flag, EWN_passenger_flag, SNE_passenger_flag,
     SNW_passenger_flag);
  input clk, reset, start, mess_traffic_flag, daytime_flag,
       white2Tminus_flag, green2yellow_flag, red_flag;
  input [7:0] pass_key;
  output need_white2Tminus_flag, need_green2yellow_flag, need_red_flag,
       reds_on_flag, ES_turning_lights_flag, WN_turning_lights_flag,
       SW_turning_lights_flag, NE_turning_lights_flag;
  output [2:0] EW_straight_lights_flag, SN_straight_lights_flag,
       EWS_passenger_flag, EWN_passenger_flag, SNE_passenger_flag,
       SNW_passenger_flag;
  wire clk, reset, start, mess_traffic_flag, daytime_flag,
       white2Tminus_flag, green2yellow_flag, red_flag;
  wire [7:0] pass_key;
  wire need_white2Tminus_flag, need_green2yellow_flag, need_red_flag,
       reds_on_flag, ES_turning_lights_flag, WN_turning_lights_flag,
       SW_turning_lights_flag, NE_turning_lights_flag;
  wire [2:0] EW_straight_lights_flag, SN_straight_lights_flag,
       EWS_passenger_flag, EWN_passenger_flag, SNE_passenger_flag,
       SNW_passenger_flag;
  wire [5:0] state;
  wire D_flag, n_0, n_1, n_2, n_3, n_5, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_25;
  wire n_26, n_27, n_28, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_54, n_55, n_57, n_58, n_59, n_61, n_62;
  wire n_63, n_64, n_65, n_67, n_68, n_69, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_104, n_105;
  wire n_106, n_107, n_109, n_110, n_111, n_112, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_145_BAR, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_176, n_178, n_179, n_180, n_181, n_182, n_183, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_195, n_196;
  wire n_197, n_198, n_199, n_200, n_201, n_202, n_203, n_205;
  wire n_206, n_207, n_208, n_209, n_210, n_211, n_212, n_213;
  wire n_215, n_216, n_217, n_218, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_239, n_240;
  wire n_242, n_243, n_245, n_246, n_247, n_248, n_249, n_250;
  wire n_251, n_252, n_253, n_254, n_255, n_256, n_257, n_259;
  wire n_260, n_261, n_262, n_263, n_264, n_265, n_266, n_267;
  wire n_268, n_269, n_270, n_271, n_272, n_273, n_274, n_275;
  wire n_276, n_277, n_278, n_279, n_280, n_281, n_282, n_283;
  wire n_284, n_285, n_286, n_287, n_288, n_289, n_290, n_291;
  wire n_292, n_293, n_294, n_295, n_296, n_297, n_298, n_299;
  wire n_300, n_301, n_302, n_303, n_308, n_309, n_310, n_336;
  wire n_337, n_347, n_349, n_350, n_354, n_355, n_362, n_363;
  wire n_364, n_367, n_368, n_370, n_371, n_372, n_373, n_374;
  wire n_376, n_377, n_408, n_409, n_410, n_411, n_412, n_413;
  wire n_414, n_415, n_416, n_417, n_418, n_420, n_421, n_422;
  wire n_12185_BAR;
  assign reds_on_flag = 1'b0;
  LHQ_X1 ES_turning_lights_flag_reg(.E (n_336), .D (n_225), .Q
       (ES_turning_lights_flag));
  LHQ_X1 \EWN_passenger_flag_reg[0] (.E (n_336), .D (n_303), .Q
       (EWN_passenger_flag[0]));
  LHQ_X1 \EWN_passenger_flag_reg[1] (.E (n_336), .D (n_298), .Q
       (EWN_passenger_flag[1]));
  LHQ_X1 \EWN_passenger_flag_reg[2] (.E (n_336), .D (n_284), .Q
       (EWN_passenger_flag[2]));
  LHQ_X1 \EWS_passenger_flag_reg[0] (.E (n_336), .D (n_295), .Q
       (EWS_passenger_flag[0]));
  LHQ_X1 \EWS_passenger_flag_reg[1] (.E (n_336), .D (n_289), .Q
       (EWS_passenger_flag[1]));
  LHQ_X1 \EWS_passenger_flag_reg[2] (.E (n_336), .D (n_254), .Q
       (EWS_passenger_flag[2]));
  LHQ_X1 \EW_straight_lights_flag_reg[0] (.E (n_336), .D (n_291), .Q
       (EW_straight_lights_flag[0]));
  LHQ_X1 \EW_straight_lights_flag_reg[1] (.E (n_336), .D (n_286), .Q
       (EW_straight_lights_flag[1]));
  LHQ_X1 \EW_straight_lights_flag_reg[2] (.E (n_336), .D (n_271), .Q
       (EW_straight_lights_flag[2]));
  LHQ_X1 NE_turning_lights_flag_reg(.E (n_336), .D (n_274), .Q
       (NE_turning_lights_flag));
  LHQ_X1 \SNE_passenger_flag_reg[0] (.E (n_336), .D (n_300), .Q
       (SNE_passenger_flag[0]));
  LHQ_X1 \SNE_passenger_flag_reg[1] (.E (n_336), .D (n_261), .Q
       (SNE_passenger_flag[1]));
  LHQ_X1 \SNE_passenger_flag_reg[2] (.E (n_336), .D (n_273), .Q
       (SNE_passenger_flag[2]));
  LHQ_X1 \SNW_passenger_flag_reg[0] (.E (n_336), .D (n_302), .Q
       (SNW_passenger_flag[0]));
  LHQ_X1 \SNW_passenger_flag_reg[1] (.E (n_336), .D (n_287), .Q
       (SNW_passenger_flag[1]));
  LHQ_X1 \SNW_passenger_flag_reg[2] (.E (n_336), .D (n_293), .Q
       (SNW_passenger_flag[2]));
  LHQ_X1 \SN_straight_lights_flag_reg[0] (.E (n_336), .D (n_301), .Q
       (SN_straight_lights_flag[0]));
  LHQ_X1 \SN_straight_lights_flag_reg[1] (.E (n_336), .D (n_279), .Q
       (SN_straight_lights_flag[1]));
  LHQ_X1 \SN_straight_lights_flag_reg[2] (.E (n_336), .D (n_296), .Q
       (SN_straight_lights_flag[2]));
  LHQ_X1 SW_turning_lights_flag_reg(.E (n_336), .D (n_275), .Q
       (SW_turning_lights_flag));
  LHQ_X1 WN_turning_lights_flag_reg(.E (n_336), .D (n_227), .Q
       (WN_turning_lights_flag));
  LHQ_X1 need_green2yellow_flag_reg(.E (n_336), .D (n_299), .Q
       (need_green2yellow_flag));
  LHQ_X1 need_red_flag_reg(.E (n_336), .D (n_294), .Q (need_red_flag));
  NAND4_X1 g11237(.A1 (n_239), .A2 (n_265), .A3 (n_288), .A4 (n_257),
       .ZN (n_303));
  NAND2_X1 g11238(.A1 (n_297), .A2 (n_236), .ZN (n_302));
  NAND3_X1 g11239(.A1 (n_292), .A2 (n_195), .A3 (n_217), .ZN (n_301));
  NAND4_X1 g11240(.A1 (n_292), .A2 (n_285), .A3 (n_236), .A4 (n_243),
       .ZN (n_300));
  OR4_X1 g11241(.A1 (n_310), .A2 (n_283), .A3 (n_218), .A4 (n_229), .Z
       (n_299));
  NAND2_X1 g11246(.A1 (n_290), .A2 (n_235), .ZN (n_298));
  NOR4_X1 g11247(.A1 (n_282), .A2 (n_256), .A3 (n_278), .A4 (n_206),
       .ZN (n_297));
  NAND4_X1 g11248(.A1 (n_220), .A2 (n_277), .A3 (n_265), .A4 (n_216),
       .ZN (n_296));
  NAND4_X1 g11249(.A1 (n_224), .A2 (n_269), .A3 (n_267), .A4 (n_199),
       .ZN (n_295));
  OR2_X1 g11253(.A1 (n_279), .A2 (n_286), .Z (n_294));
  OR2_X1 g11254(.A1 (n_364), .A2 (n_281), .Z (n_293));
  AOI21_X1 g11255(.A1 (n_178), .A2 (n_190), .B (n_282), .ZN (n_292));
  NAND4_X1 g11256(.A1 (n_239), .A2 (n_265), .A3 (n_257), .A4 (n_263),
       .ZN (n_291));
  AOI22_X1 g11257(.A1 (n_276), .A2 (n_178), .B1 (n_203), .B2 (n_191),
       .ZN (n_290));
  OAI21_X1 g11258(.A1 (n_198), .A2 (n_180), .B (n_280), .ZN (n_289));
  AOI21_X1 g11264(.A1 (n_264), .A2 (state[0]), .B (n_206), .ZN (n_288));
  NAND2_X1 g11265(.A1 (n_272), .A2 (n_226), .ZN (n_287));
  NAND2_X1 g11266(.A1 (n_270), .A2 (n_233), .ZN (n_286));
  AOI22_X1 g11269(.A1 (n_259), .A2 (n_16), .B1 (n_212), .B2 (state[2]),
       .ZN (n_285));
  NAND2_X1 g11270(.A1 (n_266), .A2 (n_245), .ZN (n_284));
  OAI21_X1 g11271(.A1 (n_220), .A2 (n_16), .B (n_268), .ZN (n_283));
  OAI22_X1 g11272(.A1 (n_262), .A2 (state[1]), .B1 (n_189), .B2 (n_16),
       .ZN (n_282));
  OAI22_X1 g11273(.A1 (n_265), .A2 (state[0]), .B1 (n_249), .B2
       (n_179), .ZN (n_281));
  AOI22_X1 g11274(.A1 (n_260), .A2 (n_185), .B1 (n_247), .B2
       (state[1]), .ZN (n_280));
  NAND2_X1 g11277(.A1 (n_252), .A2 (n_226), .ZN (n_279));
  AND2_X1 g11278(.A1 (n_259), .A2 (state[0]), .Z (n_278));
  NAND2_X1 g11279(.A1 (n_260), .A2 (n_16), .ZN (n_277));
  NAND2_X1 g11280(.A1 (n_309), .A2 (n_246), .ZN (n_276));
  NOR2_X1 g11281(.A1 (n_309), .A2 (n_182), .ZN (n_275));
  NOR2_X1 g11282(.A1 (n_309), .A2 (n_179), .ZN (n_274));
  NAND2_X1 g11283(.A1 (n_265), .A2 (n_234), .ZN (n_273));
  AOI21_X1 g11284(.A1 (n_200), .A2 (n_178), .B (n_255), .ZN (n_272));
  NAND3_X1 g11285(.A1 (n_240), .A2 (n_195), .A3 (n_246), .ZN (n_271));
  AOI22_X1 g11286(.A1 (n_203), .A2 (n_248), .B1 (n_221), .B2 (n_0), .ZN
       (n_270));
  AOI22_X1 g11287(.A1 (n_248), .A2 (state[3]), .B1 (n_187), .B2 (n_2),
       .ZN (n_269));
  AOI22_X1 g11288(.A1 (n_247), .A2 (n_182), .B1 (n_308), .B2
       (state[2]), .ZN (n_268));
  AOI22_X1 g11289(.A1 (n_210), .A2 (n_186), .B1 (n_242), .B2 (n_16),
       .ZN (n_267));
  AOI22_X1 g11290(.A1 (n_247), .A2 (n_183), .B1 (n_225), .B2 (n_1), .ZN
       (n_266));
  INV_X1 g11293(.I (n_265), .ZN (n_362));
  NAND2_X1 g11294(.A1 (n_248), .A2 (n_355), .ZN (n_265));
  OR2_X1 g11295(.A1 (n_209), .A2 (n_242), .Z (n_264));
  OR2_X1 g11296(.A1 (n_243), .A2 (n_0), .Z (n_263));
  AOI21_X1 g11297(.A1 (n_190), .A2 (state[3]), .B (n_248), .ZN (n_262));
  OAI21_X1 g11298(.A1 (n_199), .A2 (n_16), .B (n_237), .ZN (n_261));
  INV_X1 g11299(.I (n_309), .ZN (n_260));
  AOI21_X1 g11300(.A1 (n_210), .A2 (n_0), .B (n_250), .ZN (n_309));
  OAI21_X1 g11301(.A1 (n_176), .A2 (state[3]), .B (n_201), .ZN (n_259));
  AOI22_X1 g11303(.A1 (n_232), .A2 (state[3]), .B1 (n_187), .B2
       (n_180), .ZN (n_257));
  OAI22_X1 g11304(.A1 (n_231), .A2 (state[0]), .B1 (n_202), .B2
       (n_176), .ZN (n_256));
  OAI22_X1 g11305(.A1 (n_228), .A2 (state[0]), .B1 (n_208), .B2
       (n_179), .ZN (n_255));
  INV_X1 g11306(.I (n_253), .ZN (n_254));
  AOI22_X1 g11307(.A1 (n_227), .A2 (n_1), .B1 (n_222), .B2 (state[1]),
       .ZN (n_253));
  INV_X1 g11308(.I (n_251), .ZN (n_252));
  OAI22_X1 g11309(.A1 (n_228), .A2 (n_183), .B1 (n_224), .B2
       (state[1]), .ZN (n_251));
  NAND3_X1 g11310(.A1 (n_207), .A2 (n_189), .A3 (state[5]), .ZN
       (n_336));
  INV_X1 g11311(.I (n_249), .ZN (n_250));
  NAND2_X1 g11312(.A1 (n_187), .A2 (n_370), .ZN (n_249));
  NOR2_X1 g11313(.A1 (n_176), .A2 (state[4]), .ZN (n_248));
  INV_X1 g11315(.I (n_247), .ZN (n_246));
  NOR2_X1 g11316(.A1 (n_176), .A2 (n_189), .ZN (n_247));
  NAND2_X1 g11317(.A1 (n_222), .A2 (n_178), .ZN (n_245));
  NOR2_X1 g11322(.A1 (n_228), .A2 (n_182), .ZN (n_310));
  NOR2_X1 g11323(.A1 (n_220), .A2 (n_182), .ZN (n_364));
  OR2_X1 g11326(.A1 (n_176), .A2 (n_179), .Z (n_243));
  NAND2_X1 g11327(.A1 (n_176), .A2 (n_367), .ZN (n_242));
  NOR2_X1 g11329(.A1 (n_218), .A2 (n_196), .ZN (n_240));
  AOI21_X1 g11330(.A1 (n_210), .A2 (n_16), .B (n_223), .ZN (n_239));
  AOI21_X1 g11332(.A1 (n_209), .A2 (n_183), .B (n_229), .ZN (n_237));
  AOI21_X1 g11333(.A1 (n_197), .A2 (state[1]), .B (n_308), .ZN (n_236));
  NAND3_X1 g11334(.A1 (n_197), .A2 (state[3]), .A3 (n_2), .ZN (n_235));
  NAND3_X1 g11335(.A1 (n_203), .A2 (n_187), .A3 (state[2]), .ZN
       (n_234));
  NAND3_X1 g11336(.A1 (n_197), .A2 (n_182), .A3 (state[3]), .ZN
       (n_233));
  NOR2_X1 g11337(.A1 (n_211), .A2 (state[0]), .ZN (n_232));
  NOR2_X1 g11338(.A1 (n_209), .A2 (n_210), .ZN (n_231));
  NOR2_X1 g11339(.A1 (n_198), .A2 (n_349), .ZN (n_230));
  NOR2_X1 g11340(.A1 (n_211), .A2 (n_349), .ZN (n_229));
  NAND2_X1 g11341(.A1 (n_200), .A2 (state[2]), .ZN (n_228));
  NOR2_X1 g11342(.A1 (n_195), .A2 (n_2), .ZN (n_227));
  OR2_X1 g11343(.A1 (n_202), .A2 (n_201), .Z (n_226));
  NOR2_X1 g11344(.A1 (n_195), .A2 (state[0]), .ZN (n_225));
  INV_X1 g11345(.I (n_223), .ZN (n_224));
  NOR2_X1 g11346(.A1 (n_208), .A2 (n_1), .ZN (n_223));
  NOR2_X1 g11347(.A1 (n_198), .A2 (state[3]), .ZN (n_222));
  NOR2_X1 g11348(.A1 (n_211), .A2 (n_16), .ZN (n_221));
  NAND2_X1 g11350(.A1 (n_200), .A2 (n_1), .ZN (n_220));
  NOR2_X1 g11351(.A1 (n_202), .A2 (n_198), .ZN (n_218));
  OR3_X1 g11352(.A1 (n_367), .A2 (state[2]), .A3 (n_2), .Z (n_217));
  NAND3_X1 g11353(.A1 (n_183), .A2 (n_187), .A3 (state[2]), .ZN
       (n_216));
  NOR3_X1 g11354(.A1 (n_190), .A2 (n_3), .A3 (n_0), .ZN (n_215));
  HA_X1 g11355(.A (state[3]), .B (state[2]), .CO (n_370), .S
       (n_12185_BAR));
  OAI22_X1 g11356(.A1 (n_371), .A2 (state[3]), .B1 (n_12), .B2 (n_0),
       .ZN (n_363));
  OR2_X1 g11358(.A1 (n_191), .A2 (n_377), .Z (n_354));
  NOR2_X1 g11360(.A1 (n_12), .A2 (n_180), .ZN (n_213));
  NOR2_X1 g11361(.A1 (n_189), .A2 (n_2), .ZN (n_212));
  INV_X1 g11362(.I (n_211), .ZN (n_210));
  NAND2_X1 g11363(.A1 (n_190), .A2 (state[5]), .ZN (n_211));
  INV_X1 g11364(.I (n_209), .ZN (n_208));
  NOR2_X1 g11365(.A1 (n_189), .A2 (n_3), .ZN (n_209));
  NAND2_X1 g11366(.A1 (n_186), .A2 (n_190), .ZN (n_207));
  NOR2_X1 g11367(.A1 (n_181), .A2 (n_337), .ZN (n_145_BAR));
  NOR2_X1 g11368(.A1 (n_186), .A2 (state[5]), .ZN (n_206));
  NAND2_X1 g11369(.A1 (n_349), .A2 (n_180), .ZN (n_368));
  NAND2_X1 g11370(.A1 (n_183), .A2 (n_188), .ZN (n_205));
  INV_X1 g11372(.I (n_203), .ZN (n_202));
  NOR2_X1 g11373(.A1 (n_182), .A2 (n_0), .ZN (n_203));
  NAND2_X1 g11374(.A1 (n_187), .A2 (n_1), .ZN (n_201));
  INV_X1 g11375(.I (n_200), .ZN (n_199));
  NOR2_X1 g11376(.A1 (n_376), .A2 (state[3]), .ZN (n_200));
  INV_X1 g11377(.I (n_198), .ZN (n_197));
  NAND2_X1 g11378(.A1 (n_190), .A2 (n_3), .ZN (n_198));
  NOR2_X1 g11379(.A1 (n_189), .A2 (n_374), .ZN (n_196));
  INV_X1 g11380(.I (n_308), .ZN (n_195));
  NOR2_X1 g11381(.A1 (n_376), .A2 (n_180), .ZN (n_308));
  OAI22_X1 g11382(.A1 (state[2]), .A2 (state[1]), .B1 (n_1), .B2
       (n_16), .ZN (n_347));
  OAI22_X1 g11383(.A1 (state[2]), .A2 (state[5]), .B1 (n_1), .B2 (n_3),
       .ZN (n_372));
  NOR2_X1 g11387(.A1 (n_5), .A2 (n_3), .ZN (n_377));
  NOR2_X1 g11388(.A1 (state[5]), .A2 (state[4]), .ZN (n_191));
  NOR2_X1 g11389(.A1 (state[4]), .A2 (state[2]), .ZN (n_190));
  INV_X1 g11390(.I (n_189), .ZN (n_188));
  NAND2_X1 g11391(.A1 (n_0), .A2 (n_5), .ZN (n_189));
  INV_X1 g11392(.I (n_187), .ZN (n_376));
  NOR2_X1 g11393(.A1 (state[5]), .A2 (n_5), .ZN (n_187));
  INV_X1 g11394(.I (n_186), .ZN (n_185));
  NAND2_X1 g11395(.A1 (state[1]), .A2 (state[0]), .ZN (n_186));
  INV_X1 g11396(.I (n_337), .ZN (n_12));
  NOR2_X1 g11397(.A1 (n_3), .A2 (n_2), .ZN (n_337));
  INV_X1 g11398(.I (n_183), .ZN (n_182));
  NOR2_X1 g11399(.A1 (state[1]), .A2 (state[0]), .ZN (n_183));
  INV_X1 g11400(.I (n_371), .ZN (n_181));
  NAND2_X1 g11401(.A1 (n_3), .A2 (n_2), .ZN (n_371));
  NAND2_X1 g11403(.A1 (n_16), .A2 (n_0), .ZN (n_349));
  INV_X1 g11405(.I (n_180), .ZN (n_355));
  NAND2_X1 g11406(.A1 (state[1]), .A2 (state[3]), .ZN (n_180));
  NAND2_X1 g11407(.A1 (n_16), .A2 (state[0]), .ZN (n_179));
  NOR2_X1 g11409(.A1 (n_16), .A2 (state[0]), .ZN (n_178));
  NAND2_X1 g11410(.A1 (n_3), .A2 (state[0]), .ZN (n_350));
  NAND2_X1 g11411(.A1 (state[2]), .A2 (n_3), .ZN (n_176));
  NAND2_X1 g11412(.A1 (n_3), .A2 (state[3]), .ZN (n_367));
  NAND2_X1 g11414(.A1 (state[5]), .A2 (n_0), .ZN (n_373));
  NAND2_X1 g11415(.A1 (n_3), .A2 (state[1]), .ZN (n_374));
  INV_X2 g11416(.I (state[1]), .ZN (n_16));
  INV_X1 g11417(.I (state[2]), .ZN (n_1));
  INV_X1 g11419(.I (state[3]), .ZN (n_0));
  INV_X1 g11421(.I (state[0]), .ZN (n_2));
  LHQ_X1 D_flag_reg(.E (n_336), .D (n_414), .Q (D_flag));
  LHQ_X1 need_white2Tminus_flag_reg(.E (n_336), .D (n_139), .Q
       (need_white2Tminus_flag));
  DFFSNQ_X1 \state_reg[0] (.SN (1'b1), .CLK (clk), .D (n_160), .Q
       (state[0]));
  DFFSNQ_X1 \state_reg[1] (.SN (1'b1), .CLK (clk), .D (n_159), .Q
       (state[1]));
  DFFSNQ_X1 \state_reg[2] (.SN (1'b1), .CLK (clk), .D (n_164), .Q
       (state[2]));
  DFFSNQ_X1 \state_reg[3] (.SN (1'b1), .CLK (clk), .D (n_161), .Q
       (state[3]));
  DFFSNQ_X1 \state_reg[4] (.SN (1'b1), .CLK (clk), .D (n_162), .Q
       (state[4]));
  DFFSNQ_X1 \state_reg[5] (.SN (1'b1), .CLK (clk), .D (n_152), .Q
       (state[5]));
  NAND2_X1 g14032(.A1 (n_157), .A2 (n_163), .ZN (n_164));
  AOI22_X1 g14036(.A1 (n_158), .A2 (n_131), .B1 (n_140), .B2 (n_148),
       .ZN (n_163));
  OAI21_X1 g14038(.A1 (n_156), .A2 (reset), .B (n_129), .ZN (n_162));
  NAND3_X1 g14039(.A1 (n_145), .A2 (n_133), .A3 (n_154), .ZN (n_161));
  OAI21_X1 g14040(.A1 (n_155), .A2 (n_150), .B (n_147), .ZN (n_160));
  NAND3_X1 g14042(.A1 (n_153), .A2 (n_111), .A3 (n_107), .ZN (n_159));
  OAI21_X1 g14043(.A1 (n_149), .A2 (n_22), .B (n_116), .ZN (n_158));
  NOR2_X1 g14045(.A1 (n_144), .A2 (n_134), .ZN (n_157));
  AOI21_X1 g14046(.A1 (n_55), .A2 (n_132), .B (n_142), .ZN (n_156));
  AOI22_X1 g14047(.A1 (n_141), .A2 (n_115), .B1 (n_92), .B2 (n_101),
       .ZN (n_155));
  NAND4_X1 g14048(.A1 (n_58), .A2 (n_143), .A3 (n_82), .A4 (n_36), .ZN
       (n_154));
  NAND4_X1 g14049(.A1 (n_151), .A2 (n_117), .A3 (n_17), .A4 (n_85), .ZN
       (n_153));
  NOR4_X1 g14050(.A1 (n_106), .A2 (n_128), .A3 (n_110), .A4 (n_61), .ZN
       (n_152));
  NAND2_X1 g14052(.A1 (n_137), .A2 (n_16), .ZN (n_151));
  NAND2_X1 g14053(.A1 (n_136), .A2 (n_36), .ZN (n_150));
  AOI22_X1 g14054(.A1 (n_126), .A2 (n_5), .B1 (state[4]), .B2
       (green2yellow_flag), .ZN (n_149));
  AOI21_X1 g14055(.A1 (n_109), .A2 (n_18), .B (n_135), .ZN (n_148));
  AOI22_X1 g14056(.A1 (n_102), .A2 (n_130), .B1 (n_98), .B2 (n_78), .ZN
       (n_147));
  NAND4_X1 g14058(.A1 (n_138), .A2 (n_88), .A3 (n_118), .A4 (n_73), .ZN
       (n_145));
  NOR4_X1 g14059(.A1 (n_127), .A2 (n_125), .A3 (n_0), .A4 (n_37), .ZN
       (n_144));
  AOI22_X1 g14060(.A1 (n_112), .A2 (n_0), .B1 (n_371), .B2 (n_18), .ZN
       (n_143));
  NOR4_X1 g14061(.A1 (n_350), .A2 (n_122), .A3 (n_349), .A4 (state[2]),
       .ZN (n_142));
  NOR2_X1 g14062(.A1 (n_416), .A2 (n_91), .ZN (n_141));
  NAND2_X1 g14063(.A1 (n_119), .A2 (n_27), .ZN (n_140));
  AOI21_X1 g14064(.A1 (n_422), .A2 (n_105), .B (n_411), .ZN (n_139));
  NAND2_X1 g14065(.A1 (n_120), .A2 (n_27), .ZN (n_138));
  OAI21_X1 g14066(.A1 (n_104), .A2 (n_84), .B (n_75), .ZN (n_137));
  NAND3_X1 g14067(.A1 (n_75), .A2 (n_124), .A3 (n_27), .ZN (n_136));
  OAI21_X1 g14068(.A1 (n_71), .A2 (n_16), .B (n_114), .ZN (n_135));
  INV_X1 g14069(.I (n_133), .ZN (n_134));
  NAND3_X1 g14070(.A1 (n_93), .A2 (n_95), .A3 (n_78), .ZN (n_133));
  OAI22_X1 g14071(.A1 (n_99), .A2 (n_80), .B1 (n_374), .B2 (n_11), .ZN
       (n_132));
  NOR4_X1 g14072(.A1 (n_121), .A2 (n_64), .A3 (state[3]), .A4 (n_37),
       .ZN (n_131));
  NOR2_X1 g14073(.A1 (n_90), .A2 (n_74), .ZN (n_130));
  INV_X1 g14074(.I (n_128), .ZN (n_129));
  NAND2_X1 g14075(.A1 (n_96), .A2 (n_97), .ZN (n_128));
  NOR2_X1 g14076(.A1 (n_109), .A2 (state[1]), .ZN (n_127));
  NOR2_X1 g14077(.A1 (n_104), .A2 (n_81), .ZN (n_126));
  NAND2_X1 g14078(.A1 (n_94), .A2 (n_89), .ZN (n_125));
  NAND3_X1 g14079(.A1 (n_76), .A2 (n_69), .A3 (n_50), .ZN (n_124));
  OAI21_X1 g14081(.A1 (n_81), .A2 (mess_traffic_flag), .B
       (daytime_flag), .ZN (n_122));
  NOR2_X1 g14082(.A1 (n_87), .A2 (n_16), .ZN (n_121));
  INV_X1 g14083(.I (n_119), .ZN (n_120));
  AOI21_X1 g14084(.A1 (n_34), .A2 (state[0]), .B (n_86), .ZN (n_119));
  OAI21_X1 g14085(.A1 (n_54), .A2 (state[5]), .B (n_18), .ZN (n_118));
  NAND3_X1 g14086(.A1 (n_100), .A2 (n_5), .A3 (state[3]), .ZN (n_117));
  NOR3_X1 g14087(.A1 (n_63), .A2 (n_62), .A3 (state[1]), .ZN (n_116));
  AOI21_X1 g14088(.A1 (n_18), .A2 (n_65), .B (n_0), .ZN (n_115));
  AOI21_X1 g14089(.A1 (n_20), .A2 (n_52), .B (n_74), .ZN (n_114));
  OAI21_X1 g14091(.A1 (n_84), .A2 (n_51), .B (n_21), .ZN (n_112));
  NAND4_X1 g14092(.A1 (n_12), .A2 (n_71), .A3 (state[1]), .A4 (n_73),
       .ZN (n_111));
  NAND4_X1 g14093(.A1 (n_35), .A2 (n_417), .A3 (n_68), .A4 (n_83), .ZN
       (n_110));
  NAND2_X1 g14094(.A1 (n_54), .A2 (n_3), .ZN (n_109));
  NAND2_X1 g14096(.A1 (n_10), .A2 (n_78), .ZN (n_107));
  NOR2_X1 g14097(.A1 (n_57), .A2 (n_59), .ZN (n_106));
  NOR2_X1 g14098(.A1 (n_67), .A2 (n_408), .ZN (n_105));
  NAND2_X1 g14099(.A1 (n_77), .A2 (n_50), .ZN (n_104));
  NAND2_X1 g14101(.A1 (n_25), .A2 (n_65), .ZN (n_102));
  AOI21_X1 g14102(.A1 (n_2), .A2 (n_46), .B (state[3]), .ZN (n_101));
  OAI21_X1 g14103(.A1 (n_3), .A2 (n_44), .B (n_28), .ZN (n_100));
  NOR2_X1 g14104(.A1 (n_418), .A2 (n_72), .ZN (n_99));
  NOR2_X1 g14105(.A1 (n_79), .A2 (n_65), .ZN (n_98));
  NAND3_X1 g14106(.A1 (n_18), .A2 (n_39), .A3 (n_30), .ZN (n_97));
  NAND4_X1 g14107(.A1 (n_34), .A2 (n_355), .A3 (state[4]), .A4 (n_8),
       .ZN (n_96));
  OAI21_X1 g14108(.A1 (n_18), .A2 (n_20), .B (n_40), .ZN (n_95));
  AOI21_X1 g14109(.A1 (n_21), .A2 (state[5]), .B (n_18), .ZN (n_94));
  AOI22_X1 g14110(.A1 (n_25), .A2 (n_33), .B1 (n_371), .B2 (n_27), .ZN
       (n_93));
  AOI22_X1 g14111(.A1 (n_18), .A2 (n_350), .B1 (n_49), .B2 (state[1]),
       .ZN (n_92));
  OAI22_X1 g14112(.A1 (n_23), .A2 (n_31), .B1 (n_371), .B2 (n_26), .ZN
       (n_91));
  OAI22_X1 g14113(.A1 (n_145_BAR), .A2 (n_19), .B1 (n_48), .B2
       (state[1]), .ZN (n_90));
  AOI22_X1 g14114(.A1 (n_20), .A2 (n_28), .B1 (n_25), .B2 (n_47), .ZN
       (n_89));
  AOI22_X1 g14115(.A1 (n_20), .A2 (n_34), .B1 (n_25), .B2 (n_28), .ZN
       (n_88));
  AOI22_X1 g14116(.A1 (n_39), .A2 (n_5), .B1 (state[4]), .B2 (n_13),
       .ZN (n_87));
  OAI22_X1 g14117(.A1 (n_40), .A2 (state[0]), .B1 (n_3), .B2
       (red_flag), .ZN (n_86));
  NOR2_X1 g14118(.A1 (n_377), .A2 (n_37), .ZN (n_85));
  NOR2_X1 g14119(.A1 (D_flag), .A2 (n_42), .ZN (n_84));
  NAND2_X1 g14120(.A1 (n_32), .A2 (daytime_flag), .ZN (n_83));
  OR2_X1 g14121(.A1 (n_23), .A2 (n_44), .Z (n_82));
  NOR2_X1 g14122(.A1 (D_flag), .A2 (n_43), .ZN (n_81));
  NOR2_X1 g14123(.A1 (n_12185_BAR), .A2 (n_32), .ZN (n_80));
  NOR2_X1 g14124(.A1 (n_27), .A2 (state[0]), .ZN (n_79));
  AND2_X1 g14125(.A1 (state[3]), .A2 (n_30), .Z (n_78));
  OAI21_X1 g14126(.A1 (pass_key[6]), .A2 (pass_key[5]), .B (D_flag),
       .ZN (n_77));
  OAI21_X1 g14127(.A1 (pass_key[2]), .A2 (pass_key[1]), .B (D_flag),
       .ZN (n_76));
  NOR2_X1 g14128(.A1 (n_22), .A2 (state[3]), .ZN (n_75));
  INV_X1 g14129(.I (n_74), .ZN (n_73));
  NAND2_X1 g14130(.A1 (n_0), .A2 (n_30), .ZN (n_74));
  NOR2_X1 g14131(.A1 (n_368), .A2 (n_21), .ZN (n_72));
  OAI21_X1 g14132(.A1 (state[5]), .A2 (red_flag), .B (state[4]), .ZN
       (n_71));
  OAI21_X1 g14134(.A1 (pass_key[7]), .A2 (pass_key[0]), .B (n_15), .ZN
       (n_69));
  NOR3_X1 g14135(.A1 (n_363), .A2 (n_377), .A3 (reset), .ZN (n_68));
  NOR3_X1 g14136(.A1 (n_309), .A2 (n_376), .A3 (n_347), .ZN (n_67));
  OAI21_X1 g14138(.A1 (state[0]), .A2 (red_flag), .B (n_3), .ZN (n_65));
  AOI21_X1 g14139(.A1 (n_5), .A2 (red_flag), .B (n_23), .ZN (n_64));
  NOR3_X1 g14140(.A1 (n_47), .A2 (n_5), .A3 (state[0]), .ZN (n_63));
  NOR3_X1 g14141(.A1 (n_3), .A2 (state[4]), .A3 (n_13), .ZN (n_62));
  AND3_X1 g14142(.A1 (state[5]), .A2 (state[3]), .A3 (n_31), .Z (n_61));
  OAI21_X1 g14144(.A1 (state[3]), .A2 (state[2]), .B (n_373), .ZN
       (n_59));
  OAI22_X1 g14145(.A1 (n_337), .A2 (state[1]), .B1 (n_377), .B2 (n_16),
       .ZN (n_58));
  OAI22_X1 g14146(.A1 (n_367), .A2 (n_1), .B1 (n_3), .B2 (n_16), .ZN
       (n_57));
  AOI22_X1 g14148(.A1 (n_354), .A2 (n_7), .B1 (n_370), .B2 (state[4]),
       .ZN (n_55));
  AOI22_X1 g14149(.A1 (n_2), .A2 (green2yellow_flag), .B1 (state[0]),
       .B2 (red_flag), .ZN (n_54));
  OAI22_X1 g14151(.A1 (n_13), .A2 (state[5]), .B1 (state[0]), .B2
       (n_3), .ZN (n_52));
  INV_X1 g14152(.I (n_50), .ZN (n_51));
  NOR2_X1 g14153(.A1 (n_9), .A2 (mess_traffic_flag), .ZN (n_50));
  INV_X1 g14154(.I (n_48), .ZN (n_49));
  NOR2_X1 g14155(.A1 (n_377), .A2 (n_2), .ZN (n_48));
  NAND2_X1 g14156(.A1 (n_3), .A2 (white2Tminus_flag), .ZN (n_47));
  NAND2_X1 g14157(.A1 (n_3), .A2 (start), .ZN (n_46));
  NOR2_X1 g14159(.A1 (state[0]), .A2 (daytime_flag), .ZN (n_44));
  INV_X1 g14160(.I (n_42), .ZN (n_43));
  NOR2_X1 g14161(.A1 (pass_key[4]), .A2 (pass_key[3]), .ZN (n_42));
  NOR2_X1 g14162(.A1 (n_362), .A2 (n_308), .ZN (n_41));
  INV_X1 g14163(.I (n_40), .ZN (n_39));
  NAND2_X1 g14164(.A1 (n_3), .A2 (n_11), .ZN (n_40));
  NAND2_X1 g14165(.A1 (n_347), .A2 (state[3]), .ZN (n_38));
  INV_X1 g14166(.I (n_37), .ZN (n_36));
  NAND2_X1 g14167(.A1 (n_1), .A2 (n_8), .ZN (n_37));
  NAND2_X1 g14168(.A1 (n_420), .A2 (n_3), .ZN (n_35));
  INV_X1 g14169(.I (n_33), .ZN (n_34));
  NAND2_X1 g14170(.A1 (n_3), .A2 (n_13), .ZN (n_33));
  NOR2_X1 g14171(.A1 (state[5]), .A2 (state[2]), .ZN (n_32));
  NOR2_X1 g14172(.A1 (state[0]), .A2 (n_9), .ZN (n_31));
  NOR2_X1 g14173(.A1 (n_1), .A2 (reset), .ZN (n_30));
  NAND2_X1 g14175(.A1 (n_3), .A2 (red_flag), .ZN (n_28));
  INV_X1 g14176(.I (n_27), .ZN (n_26));
  NOR2_X1 g14177(.A1 (state[1]), .A2 (state[4]), .ZN (n_27));
  NOR2_X1 g14179(.A1 (n_16), .A2 (n_5), .ZN (n_25));
  NAND2_X1 g14180(.A1 (state[1]), .A2 (state[5]), .ZN (n_23));
  NAND2_X1 g14181(.A1 (state[0]), .A2 (n_3), .ZN (n_22));
  NOR2_X1 g14182(.A1 (n_2), .A2 (state[1]), .ZN (n_21));
  INV_X1 g14183(.I (n_20), .ZN (n_19));
  NOR2_X1 g14184(.A1 (n_16), .A2 (state[4]), .ZN (n_20));
  INV_X1 g14185(.I (n_18), .ZN (n_17));
  NOR2_X1 g14186(.A1 (state[1]), .A2 (n_5), .ZN (n_18));
  INV_X1 g14202(.I (state[4]), .ZN (n_5));
  INV_X2 g14224(.I (state[5]), .ZN (n_3));
  INV_X1 g14280(.I (D_flag), .ZN (n_15));
  INV_X1 g14281(.I (red_flag), .ZN (n_14));
  INV_X1 g14282(.I (green2yellow_flag), .ZN (n_13));
  INV_X1 g14284(.I (white2Tminus_flag), .ZN (n_11));
  INV_X1 g14285(.I (n_374), .ZN (n_10));
  INV_X1 g14286(.I (daytime_flag), .ZN (n_9));
  INV_X1 g14287(.I (reset), .ZN (n_8));
  INV_X1 g14288(.I (n_370), .ZN (n_7));
  OR3_X1 g2(.A1 (n_222), .A2 (n_412), .A3 (n_215), .Z (n_408));
  INV_X1 g4(.I (n_410), .ZN (n_411));
  AOI21_X1 g14297(.A1 (n_370), .A2 (state[5]), .B (n_409), .ZN (n_410));
  OR3_X1 g3(.A1 (n_230), .A2 (n_213), .A3 (n_377), .Z (n_409));
  NOR2_X1 g14298(.A1 (n_205), .A2 (state[5]), .ZN (n_412));
  OAI21_X1 g14299(.A1 (n_413), .A2 (n_35), .B (n_228), .ZN (n_414));
  AND2_X1 g14300(.A1 (n_220), .A2 (n_38), .Z (n_413));
  NOR2_X1 g14301(.A1 (n_415), .A2 (state[0]), .ZN (n_416));
  AOI21_X1 g14302(.A1 (n_3), .A2 (n_14), .B (n_25), .ZN (n_415));
  NAND2_X1 g14303(.A1 (n_372), .A2 (state[1]), .ZN (n_417));
  AOI21_X1 g14304(.A1 (n_374), .A2 (state[3]), .B (state[5]), .ZN
       (n_418));
  AOI21_X1 g14306(.A1 (state[2]), .A2 (state[4]), .B (n_190), .ZN
       (n_420));
  OAI21_X1 g14307(.A1 (n_364), .A2 (n_421), .B (n_309), .ZN (n_422));
  OAI21_X1 g14308(.A1 (n_220), .A2 (n_179), .B (n_41), .ZN (n_421));
endmodule

module top_interface(clk, reset, start, pass_key, mess_traffic_flag,
     daytime_flag, EW_straight_lights_flag, SN_straight_lights_flag,
     ES_turning_lights_flag, WN_turning_lights_flag,
     SW_turning_lights_flag, NE_turning_lights_flag,
     EWS_passenger_flag, EWN_passenger_flag, SNE_passenger_flag,
     SNW_passenger_flag);
  input clk, reset, start, mess_traffic_flag, daytime_flag;
  input [7:0] pass_key;
  output [2:0] EW_straight_lights_flag, SN_straight_lights_flag,
       EWS_passenger_flag, EWN_passenger_flag, SNE_passenger_flag,
       SNW_passenger_flag;
  output ES_turning_lights_flag, WN_turning_lights_flag,
       SW_turning_lights_flag, NE_turning_lights_flag;
  wire clk, reset, start, mess_traffic_flag, daytime_flag;
  wire [7:0] pass_key;
  wire [2:0] EW_straight_lights_flag, SN_straight_lights_flag,
       EWS_passenger_flag, EWN_passenger_flag, SNE_passenger_flag,
       SNW_passenger_flag;
  wire ES_turning_lights_flag, WN_turning_lights_flag,
       SW_turning_lights_flag, NE_turning_lights_flag;
  wire green2yellow_flag, need_green2yellow_flag, need_red_flag,
       need_white2Tminus_flag, red_flag, reds_on_flag,
       white2Tminus_flag;
  clock_divider control_delay(reset, clk, 1'b0, need_white2Tminus_flag,
       need_green2yellow_flag, need_red_flag, white2Tminus_flag,
       green2yellow_flag, red_flag);
  fsm control_fsm(clk, reset, start, pass_key, mess_traffic_flag,
       daytime_flag, white2Tminus_flag, green2yellow_flag, red_flag,
       need_white2Tminus_flag, need_green2yellow_flag, need_red_flag,
       reds_on_flag, EW_straight_lights_flag, SN_straight_lights_flag,
       ES_turning_lights_flag, WN_turning_lights_flag,
       SW_turning_lights_flag, NE_turning_lights_flag,
       EWS_passenger_flag, EWN_passenger_flag, SNE_passenger_flag,
       SNW_passenger_flag);
endmodule

